// ? CHAPTER 1 

// ! q2

// alert("Error! Please enter a valid password");

// ! q3

// alert("Welcome to JS Land... \nHappy Coding!");

// ! q4

// alert("Welcome to JS Land...");
// alert("Happy Coding!\n"
// +"prevent this page from creating additional dialogs");

// ! q5
// console.log("Hello... i can run js through my web browser's Console");

// ! q6 
// another file name : q6-q7

// ! q7 
// another file name : q6-q7

// ? CHAPTER 2 

// ! q1
// var username;

// ! q2
// var myname = "Sajjad Huusain";

// ! q3
// var message = "Hello World";
// alert(message);

// ! q4
// var name1 = "Sajjad Hussain";
// var age = "22";
// alert(name1);
// alert(age  + " years old")
// alert("Certified Mobile Application development")

// ! q5
// var q_variable = "PIZZA\n" + "pIZZ\n" + "PIZ\n" + "pI\n" + "p\n"
// alert(q_variable)  


// ! q6
// var email = "narejo220@gmail.com"
// alert("my email address is " + email)

// ! q7
// var book = "A smarter way to learn JavaScript"
// alert("I am trying to learn from the book " + book)

// ! q8 
// var br=  "yah! i can write html content through javascript"
// document.write(br)

// ! q9
// var show_string ="▬▬▬▬▬▬▬▬▬ஜ۩۞۩ஜ▬▬▬▬▬▬▬▬▬"
// alert(show_string) 